### ISSUE TITLE
Add plausible option for Nuxt

### ISSUE THREAD

**Issue by Atinux** [moritzsternemann/vue-plausible#2]
Hi @moritzsternemann 

Great work on this module, I think it would be nice to support a `plausible` property in the `nuxt.config.js` as option:
https://github.com/moritzsternemann/vue-plausible/blob/main/src/nuxt-module.ts#L6

We usually use [defu](https://github.com/nuxt-contrib/defu) for handling defaults options and merging with `moduleOptions` , see example on https://github.com/bdrtsky/nuxt-ackee/blob/master/lib/module.js#L2-L17

**Comment by moritzsternemann** [comment]
Hey @Atinux!

I was actually already looking into adding support for the plausible property, thanks for pointing me in the right direction!
This fill find it's way into the next release 👍
